# Generated by Django 4.2.27 on 2026-01-09 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
