# Generated by Django 4.2.27 on 2026-01-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_product_created_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('r2_score', models.FloatField()),
                ('mae', models.FloatField()),
                ('mape', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('confidence_lower', models.FloatField()),
                ('confidence_upper', models.FloatField()),
                ('model_used', models.CharField(max_length=50)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['product', 'forecast_date'], name='forecasting_product_e674e0_idx')],
            },
        ),
    ]
